import { useState } from 'react'
import { query } from '../lib/api'
import useData from '../lib/useData'
import { PageTitle, Icon, State, Field } from '../components/UI'

const events = { login_success: 'Acceso exitoso', login_failed: 'Acceso fallido', mfa_failed: 'Fallo MFA', account_locked: 'Cuenta bloqueada', product_created: 'Producto creado', product_updated: 'Producto editado', product_deleted: 'Producto eliminado', stock_updated: 'Stock actualizado' }
export default function Audit() {
  const [filters, setFilters] = useState({ event: '', from: '', to: '', page: 1 })
  const { data, loading, error } = useData(`/audit/?${query(filters)}`)
  const change = (key, value) => setFilters({ ...filters, [key]: value, page: 1 })
  return <><PageTitle title="Auditoría" description="Un registro transparente de accesos y cambios en el inventario."/><div className="read-only"><Icon name="shield" size={16}/> Historial de solo lectura. Los registros se conservan aunque se elimine un producto.</div><section className="panel"><div className="filters"><Field label="Evento"><select value={filters.event} onChange={e => change('event', e.target.value)}><option value="">Todos los eventos</option>{Object.entries(events).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></Field><Field label="Desde"><input type="date" value={filters.from} max={filters.to || undefined} onChange={e => change('from', e.target.value)}/></Field><Field label="Hasta"><input type="date" value={filters.to} min={filters.from || undefined} onChange={e => change('to', e.target.value)}/></Field></div><State loading={loading} error={error} empty={!data?.results.length}><div className="table-scroll"><table><thead><tr><th>Fecha y hora</th><th>Evento</th><th>Usuario</th><th>Tienda / Producto</th><th>Detalle</th></tr></thead><tbody>{data?.results.map(row => <tr key={row.id}><td className="nowrap">{new Date(row.created_at).toLocaleString('es-PE', { timeZone: 'America/Lima' })}</td><td><span className={`badge ${row.event.includes('failed') || row.event === 'account_locked' ? 'warning' : 'neutral'}`}>{events[row.event] || row.event}</span></td><td>{row.actor || 'No identificado'}</td><td><strong>{row.store_name || '—'}</strong><small>{row.product_name}{row.sku ? ` · ${row.sku}` : ''}</small></td><td>{row.detail}{row.old_stock !== null && row.new_stock !== null && <small className="stock-change">Stock: {row.old_stock} → {row.new_stock}</small>}</td></tr>)}</tbody></table></div></State><div className="panel-footer pagination"><span>{data?.count ?? 0} eventos · Página {filters.page}</span><div className="button-group"><button className="secondary small" disabled={loading || filters.page <= 1} onClick={() => setFilters({ ...filters, page: filters.page - 1 })}>Anterior</button><button className="secondary small" disabled={loading || !data || filters.page * 50 >= data.count} onClick={() => setFilters({ ...filters, page: filters.page + 1 })}>Siguiente</button></div></div></section></>
}
